# Generated by Django 6.0.6 on 2026-06-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('staff_id', models.CharField(max_length=50, unique=True, verbose_name='ID raqami (Karta/Guvohnoma)')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('teacher', "O'qituvchi"), ('student', 'Talaba'), ('staff', 'Xodim')], default='staff', max_length=20, verbose_name='Roli')),
                ('default_hours', models.PositiveIntegerField(default=8, verbose_name='Standart kunlik ish soati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin panelga kira oladi')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.TimeField(verbose_name='Kelgan vaqti')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Ketgan vaqti')),
                ('minutes_spent', models.PositiveIntegerField(default=0, verbose_name='Ishlagan vaqti (daqiqa)')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('early_out_minutes', models.PositiveIntegerField(default=0, verbose_name='Erta ketish (daqiqa)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(help_text='Masalan: 09:00', verbose_name='Ish boshlanish vaqti')),
                ('expected_hours', models.PositiveIntegerField(default=8, verbose_name='Ish vaqti (soat)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik Grafik',
                'verbose_name_plural': 'Kunlik Grafiklar',
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
